- hosts: all
  become: yes
  tasks:

    # FIXME
    # Ansible's apt_repository module doesn't work correcty with Linux Mint,
    # see https://github.com/ansible/ansible/issues/4587
    # Also, the filenames that are checked for existence are hardcoded :(
    - name: Add official git PPA
      command: >
        add-apt-repository --yes ppa:git-core/ppa
        creates=/etc/apt/sources.list.d/git-core-ppa-trusty.list
      register: git_ppa_status

      # Officially recommended replacement for deprecated git filter-branch
    - name: download git filter-repo
      get_url:
        url: https://raw.githubusercontent.com/newren/git-filter-repo/master/git-filter-repo
        dest: "{{ ansible_env.HOME }}/bin/git-filter-repo"
        mode: 0755
      become: no

    - name: update apt cache
      apt: update_cache=yes
      when: git_ppa_status.changed

    - name: add asciinema PPA
      apt_repository:
        repo: ppa:zanchey/asciinema
        codename: "{{ dist_override | default(omit) }}"
        filename: "asciinema"

    - name: Install latest versions of apt packages
      apt:
        name:
          - asciinema   # for recording teminal sessions
          - build-essential
          - flip
          - git
          - htop
          - ipython
          - jq  # for manipulating json
          - gnupg
          - openssh-server
          - pandoc  # for diffing binary documents
          - python-numpy
          - python-scipy
          - python-matplotlib
          - python-tk
          - sshfs
          - ranger
          - tmux
          - trash-cli
          - tree
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600

