- hosts: all
  tasks:

      # fzf isn't available in Ubuntu repos - configure Debian Buster source
      # (unless we're already on Debian)
    - when: ansible_distribution != "Debian"
      become: yes
      block:

        - name: add debian buster apt key
          apt_key:
            url: "https://ftp-master.debian.org/keys/release-10.asc"

        - name: add debian buster apt repo
          apt_repository:
            repo: "deb http://deb.debian.org/debian buster main"
            filename: debian-buster

        - name: lower apt priority for buster packages
          copy:
            dest: /etc/apt/preferences.d/01-debian-buster.pref
            content: |
              # only use buster repos if package is unavailable elsewhere
              Package: *
              Pin: release n=buster
              Pin-Priority: 200

    - name: install fzf
      apt:
        name: fzf
      become: yes

    - name: get customized fzf repo
      git:
        repo: https://github.com/jan-warchol/fzf
        dest: "{{ fzf_home }}"

    - name: add upstream to fzf repo
      blockinfile:
        block: |
          [remote "upstream"]
                  url = https://github.com/junegunn/fzf.git
                  fetch = +refs/heads/*:refs/remotes/upstream/*
        dest: "{{ fzf_home }}/.git/config"

    - name: ensure directories exist
      file:
        dest: "{{ ansible_env.HOME }}/data/fzf/"
        state: directory
        mode: 0700

    - name: ensure fzf history file exists
      copy:
        dest: "{{ fzf_history }}"
        content: ""
        force: no
