- hosts: all
  tasks:

    - name: Install vim
      apt:
        name: vim-gnome  # default `vim` package doesn't have clipboard support
      become: yes

    - name: ensure config directories exist
      file:
        dest: "{{ ansible_env.HOME }}/.vim/{{ item }}"
        state: directory
      with_items:
        - autoload  # for vim-plug
        - swap  # global dir for swapfiles
        - backup  # global dir for backup files
        - colors  # for colorschemes

    # The nice thing about vim-plug (https://github.com/junegunn/vim-plug)
    # is that it can be installed just by downloading one file.
    - name: install vim-plug plugin manager
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

    - name: install selenized color palette
      get_url:
        url: https://raw.githubusercontent.com/jan-warchol/selenized/master/editors/vim/colors/selenized.vim
        dest: "{{ ansible_env.HOME }}/.vim/colors/selenized.vim"
        force: yes

    - name: install plugins (only first time)
      shell: vim +PlugInstall +qall creates={{ ansible_env.HOME }}/.vim/plugged

