- hosts: all
  become: yes
  tasks:

    # FIXME
    # Ansible's apt_repository module doesn't work correcty with Linux Mint,
    # see https://github.com/ansible/ansible/issues/4587
    # Also, the filenames that are checked for existence are hardcoded :(

    - name: Add official git PPA
      command: >
        add-apt-repository --yes ppa:git-core/ppa
        creates=/etc/apt/sources.list.d/git-core-ppa-trusty.list
      register: git_ppa_status

    - name: update apt cache
      apt: update_cache=yes
      when: git_ppa_status.changed

    - name: Install latest versions of apt packages
      apt:
        name:
          - build-essential
          - flip
          - git
          - htop
          - ipython
          - gnupg
          - openssh-server
          - pass
          - python-pip
          - python-dev
          - python-virtualenv
          - python-numpy
          - python-scipy
          - python-matplotlib
          - python-tk
          - sshfs
          - ranger
          - tmux
          - trash-cli
          - tree
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600
