- name: System-wide software installation
  hosts: all
  become: yes
  tasks:

    - name: Add official git PPA
      apt_repository:
        repo: ppa:git-core/ppa
        codename: "{{ dist_override | default(omit) }}"
        filename: "git"

    - name: add asciinema PPA
      apt_repository:
        repo: ppa:zanchey/asciinema
        codename: "{{ dist_override | default(omit) }}"
        filename: "asciinema"

    - name: Install latest versions of apt packages
      apt:
        name:
          - asciinema   # for recording teminal sessions
          - build-essential
          - flip
          - git
          - htop
          - ipython
          - jq  # for manipulating json
          - gnupg
          - openssh-server
          - pandoc  # for diffing binary documents
          - python-numpy
          - python-scipy
          - python-matplotlib
          - python-tk
          - sshfs
          - ranger
          - tmux
          - trash-cli
          - tree
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600


- name: User-level software installation
  hosts: all
  tasks:

      # Officially recommended replacement for deprecated git filter-branch
    - name: download git filter-repo
      get_url:
        url: https://raw.githubusercontent.com/newren/git-filter-repo/master/git-filter-repo
        dest: "{{ ansible_env.HOME }}/bin/git-filter-repo"
        mode: 0755

    - name: download tig commit picker
      get_url:
        url: https://raw.githubusercontent.com/jonas/tig/master/contrib/tig-pick
        dest: "{{ ansible_env.HOME }}/bin/tgp"
        mode: 0755
