- name: Install ansible and download my playbooks for system management
  hosts: all
  tasks:
      # Ansible from official repos is ancient - use PPA
    - name: add ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
        codename: xenial
      become: yes

    - name: install latest Ansible
      apt: name=ansible state=latest
      become: yes

    - name: clone ansible-system-setup repository
      git: 
        repo: https://github.com/jan-warchol/ansible-system-setup/
        dest: "{{ ansible_setup_path }}"
        version: devel
      register: task_result
      failed_when:
        - task_result is failed
        - '"Local modifications exist in repository" not in task_result.msg'

    - name: update ansible-system-setup remote
      lineinfile:
        dest: "{{ ansible_setup_path }}/.git/config"
        regexp: url = .*ansible-system-setup
        line: "	url = git@github.com:jan-warchol/ansible-system-setup.git"

      # I don't want to accidentally commit something with my work email.
    - name: override git authorship setting in ansible-system-setup
      blockinfile:
        dest: "{{ ansible_setup_path }}/.git/config"
        block: |
          [user]
            name = Jan Warchoł
            email = jan.warchol@gmail.com
      # don't use "inventory_hostname in groups.xxx" construct
      # because it fails when group xxx is not defined.  This is better.
      when: "'work_computers' in group_names"
