- name: Install ansible and download my playbooks for system management
  hosts: all
  tasks:
      # Ansible from official repos is ancient - use PPA
    - name: add ansible PPA
      apt_repository:
        repo: ppa:ansible/ansible
        codename: "{{ dist_override | default(omit) }}"
        filename: ansible
      become: yes

    - name: install latest Ansible
      apt: name=ansible state=latest
      become: yes

    - name: clone ansible-system-setup repository
      git: 
        repo: https://github.com/jan-warchol/ansible-system-setup/
        dest: "{{ ansible_setup_path }}"
        version: devel
      register: task_result
      failed_when:
        - task_result is failed
        - '"Local modifications exist in repository" not in task_result.msg'

    - name: configure git user email
      git_config:
        key: user.email
        value: jan.warchol@gmail.com
        repo: "{{ ansible_setup_path }}"

    - name: update ansible-system-setup remote
      lineinfile:
        dest: "{{ ansible_setup_path }}/.git/config"
        regexp: url = .*ansible-system-setup
        line: "	url = git@github.com:jan-warchol/ansible-system-setup.git"
