- import_playbook: codility-aws-setup.yml

- name: Install tools needed for work with kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Add kubernetes APT key
      apt_key:
        data: "{{ lookup('file', 'files/google-packages-signing-key.asc') }}"

    - name: add kubernetes APT repository
      apt_repository:
        # why xenial is hardcoded in instructions from
        # https://kubernetes.io/docs/tasks/tools/install-kubectl/ ?
        repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
        filename: kubernetes

    - name: install kubectl
      apt:
        name: kubectl
        state: latest
