- hosts: all
  become: yes
  tasks:

    - name: Add Google Chrome APT key
      apt_key:
        data: "{{ lookup('file', 'files/chrome-linux-signing-key.pub') }}"

    - name: add Google Chrome APT repository
      apt_repository:
        repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
        filename: google-chrome

    - name: install Google Chrome
      apt:
        name: google-chrome-stable
        state: latest
