- name: Install packages relevant to graphical desktop
  hosts: all
  become: yes
  tasks:

    - name: add apt key for Google Chrome
      apt_key:
        data: "{{ lookup('file', 'apt-keys/google_linux_signing_key.asc') }}"

    - name: add apt repository for Google Chrome
      apt_repository:
        repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
        filename: google-chrome

    # https://github.com/odeke-em/drive/
    # alternative project that may be worth checking out:
    # https://github.com/gdrive-org/gdrive
    - name: add Google Drive cli PPA
      apt_repository:
        repo: ppa:twodopeshaggy/drive
        codename: "{{ dist_override | default(omit) }}"
        filename: google-drive

    - name: add redshift PPA
      apt_repository:
        repo: ppa:dobey/redshift-daily
        codename: "{{ dist_override | default(omit) }}"
        filename: redshift

    - name: Install latest versions of apt packages
      apt:
        name:
          - baobab
          - dconf-cli
          - dconf-editor   # desktop environment configuration
          - drive   # CLI for google drive
          - firefox   # make sure firefox is updated - my package manager
                      # didn't want to update it on its own
          - gitk
          - google-chrome-stable
          - gparted
          - indicator-multiload
          - kate
          - keepass2
          - xdotool   # library for auto-type in keepass
          - libdvdread4   # DVD decryption
            # at least one of these 3 packages is needed for okular to open pdfs
          - libnotify-bin  # for system notifications
          - kdelibs5-plugins
          - kdelibs5-data
          - oxygen-icon-theme
          - okular
          - redshift   # for adjusting screen color temperature
          - usb-creator-gtk  # for creating USB drives for OS installation
          - vim-gnome
          - vlc
          - stopwatch   # time tracking
          - xbacklight   # changing screen brightness
          - xsel   # copying and pasting from middle-mouse-button clipboard
          - xclip   # accessing clipboard from cli, needed by pass
          # - xserver-xorg-input-synaptics  # for managing touchpad
          - gimp
          #- guake
          #- imagemagick
          #- kompare
        state: latest
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600
