- hosts: all
  vars:
    bcompare_version: "4.3.4.24657"
  tasks:
    - name: download Beyond Compare .deb file
      get_url:
        url:
          "http://www.scootersoftware.com/\
           bcompare-{{ bcompare_version }}_amd64.deb"
        dest: /tmp/bcompare-{{ bcompare_version }}.deb

    - name: install Beyond Compare
      apt: deb=/tmp/bcompare-{{ bcompare_version }}.deb
      become: yes

