Vagrant.configure(2) do |config|
    config.vm.define "vm"
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.123.11"
    config.vm.provision "ansible" do |ans|
        ans.playbook = "../configure-user.yml"
        ans.groups = { "my_computers" => ["vm"] }
    end
end
