# password management playbook includes localhost, so we have to override
# global variable definition because there is no such entry as hosts/localhost-user
# in password-store. Note that we cannot use
#
#     "{{ lookup('passwordstore', 'hosts/' + ansible_hostname + '-user') }}"
#
# because ansible_hostname is not defined at the moment of running the lookup.
ansible_become_password: ""
