- name: Install tools for managing development VMs
  hosts: all
  become: yes
  tasks:

    - name: add apt keys
      apt_key:
        data: "{{ lookup('file', item) }}"
      loop:
        - ../apt-keys/oracle_apt_key.asc
        - ../apt-keys/hashicorp_archive_key.asc

    - name: add VirtualBox repo
      apt_repository:
        repo:
          "deb http://download.virtualbox.org/virtualbox/debian \
           {{ dist_override | default(ansible_distribution_release) }} contrib"
        filename: virtualbox

    - name: add Vagrant repo
      apt_repository:
        repo:
          "deb https://apt.releases.hashicorp.com \
          {{ dist_override | default(ansible_distribution_release) }} main"
        filename: hashicorp

    - name: install VirtualBox and Vagrant
      apt:
        name:
          - virtualbox
          - vagrant
        state: latest
