# Limestone is a family of color themes for IDEs and text editors.
# https://github.com/jan-warchol/limestone-colors
#
# prerequisites:
# - git
# - credentials for accessing my repos over ssh configured

- name: Setup tools for work on Limestone project
  hosts: all
  vars:
    limestone_repo: "{{ github_url }}jan-warchol/limestone-colors.git"
    limestone_path: "{{ ansible_env.HOME }}/src/limestone-colors"
    # note: this repo is private
    code_samples_repo: "{{ github_url }}jan-warchol/code-samples.git"
    code_samples_base_path: "{{ ansible_env.HOME }}/src/code-samples"

  tasks:

    # Global settings
    ############################################################

    - name: install sublime apt key
      apt_key:
        data: "{{ lookup('file', inventory_dir + '/apt-keys/sublime-apt-key.asc') }}"
      become: yes

    - name: install microsoft apt key
      apt_key:
        data: "{{ lookup('file', inventory_dir + '/apt-keys/microsoft-apt-signing-key.asc') }}"
      become: yes

    - name: install apt repo for vscode
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        codename: "{{ dist_override | default(omit) }}"
        filename: vscode
      become: yes

    - name: install apt repo for sublime
      apt_repository:
        repo: deb https://download.sublimetext.com/ apt/stable/
        codename: "{{ dist_override | default(omit) }}"
        filename: sublime
      become: yes

    - name: install IDEs for testing limestone
      apt:
        name:
          - code
          - sublime-text
      become: yes

    - name: ensure config directories exist
      file:
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      loop:
        - ".vscode/extensions"
        - ".config/Code/User"

    - name: configure vscode shortcuts
      copy:
        content: |
          // Place your key bindings in this file to override the defaults
          [
              {
                  "key": "ctrl+d",
                  "command": "editor.action.inspectTMScopes"
              }
          ]
        dest: "{{ ansible_env.HOME }}/.config/Code/User/keybindings.json"
        backup: yes  # in case I've made further modifications

    - name: link limestone theme to .extensions
      file:
        src: "{{ limestone_path }}/vscode"
        dest: "{{ ansible_env.HOME }}/.vscode/extensions/limestone-dev"
        state: link
        force: yes  # repo will be cloned in a later step

    # - name: install other vscode extensions


    # Configure VS code transparency
    ############################################################

      # instructions from
      # https://dev.to/emmanuelnk/how-to-be-cool-and-make-vscode-transparent-56ib
    - name: install additional packages
      apt:
        name: devilspie
      become: yes

    - name: ensure config directories exist
      file:
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
      loop:
        - ".devilspie"
        - ".config/systemd/user/"

    - name: configure devilspie service
      copy:
        content: |
          [Unit]
          Description=Devilspie

          [Service]
          ExecStart=/usr/bin/devilspie

          [Install]
          WantedBy=default.target
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/devilspie.service"

    - name: manage devilspie service
      systemd:
        daemon_reload: yes
        name: devilspie
        enabled: yes
        state: started
        scope: user


    - name: configure devilspie vscode transparency
      copy:
        content: |
          ( if
          ( contains ( window_class ) "Code" )
          ( begin
          ( spawn_async (str "xprop -id " (window_xid) " -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY 0xdfffffff") )
          )
          )
        dest: "{{ ansible_env.HOME }}/.devilspie/vscode_transparent.ds"


    # Repository setup
    ############################################################

    - name: clone limestone git repo
      git:
        repo: "{{ limestone_repo }}"
        dest: "{{ limestone_path }}"
        update: no  # don't mess with existing repo

    - name: clone code samples repo
      git:
        repo: "{{ code_samples_repo }}"
        dest: "{{ item }}"
        update: no  # don't mess with existing repo
      loop:
        - "{{ code_samples_base_path }}-A"
        - "{{ code_samples_base_path }}-B"

    - name: ensure .vscode dir exists
      file:
        dest: "{{ item }}/.vscode"
        state: directory
      loop:
        - "{{ code_samples_base_path }}-A"
        - "{{ code_samples_base_path }}-B"
        - "{{ limestone_path }}"

    - name: configure per-workspace vscode themes
      copy:
        # it doesn't really matter which theme I set initially - as long as
        # this is present, consecutive theme changes will be saved locally.
        content: |
          {
              "workbench.colorTheme": "Limestone 0.8"
          }
        dest: "{{ item }}/.vscode/settings.json"
      loop:
        - "{{ code_samples_base_path }}-A"
        - "{{ code_samples_base_path }}-B"
        - "{{ limestone_path }}"
